### ISSUE TITLE
Applications

### ISSUE THREAD

**Issue by dselivanov** [zachmayer/rbm#18]
Any applications/use-cases where RBMs were useful for you? Would be nice to have in wiki/vignette...

**Comment by zachmayer** [comment]
I never found any good applications for RBMs.  [TSNE](https://cran.r-project.org/web/packages/Rtsne/index.html) is better for dimensionality reduction,  and deep networks (e.g. with [mxnet](https://github.com/dmlc/mxnet/tree/master/R-package)) work better without pre-training.
